swagger: "2.0"
info:
  version: "0.0.1"
  title: API template
host: localhost:8080
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /models:
    x-swagger-router-controller: create
    post:
      tags:
        - BaseModel
      description: Ofuscates the given url
      parameters:
        - name: model
          in: body
          required: true
          schema:
            $ref: '#/definitions/BaseModel'
      operationId: createAction
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /docs:
    x-swagger-pipe: swagger_raw

definitions:
  BaseModel:
    type: object
    description: BaseModel object
    properties:
      propertyA:
        type: string 
        description: The first property of the object
      propertyB:
        type: number 
        description: The second property of the object
    required:
      - propertyA
      - propertyB
  SuccessResponse:
    required:
      - apiVersion
      - method
      - params
      - statusCode
      - data
    type: object
    properties:
      apiVersion:
        type: string
        description: The current version of the API
      method:
        type: string
        description: The executed method
      params:
        type: object
        description: An object with all the params used to execute the method
      statusCode:
        type: number
        description: The response HTTP status code
      data:
        type: array
        description: An array with all the data returned by the server
        items:
          type: object

  ErrorResponse:
    required:
      - apiVersion
      - method
      - params
      - statusCode
      - errors
    type: object
    properties:
      apiVersion:
        type: string
        description: The current version of the API
      method:
        type: string
        description: The executed method
      params:
        type: object
        description: An array with all the params used to execute the method
      statusCode:
        type: number
        description: The response HTTP status code
      errors:
        type: array
        description: An array with all the errors
        items:
          type: object
